### ISSUE TITLE
Logged out user can't delete items in the cart

### ISSUE THREAD

**Issue by BlackStone8960** [miyabitanimchi/ciccc-react-midterm-team-project#21]

**Comment by miyabitanimchi** [comment]
- **Problem detail:** When a user who hasn't logged in tries to delete items, the error "TypeError: Cannot read property 'uid' of null" occurs.

- **Cause:** Without login, the value of "user" gets null since there is no information of a logged in user.

- **Solution:** Added a conditional as below:
`setProductsAddedToCart(newAddedProductsArr);`
    `if (user) {`
    `localStorage.removeItem(user.uid);`
    `localStorage.setItem(user.uid, JSON.stringify(newAddedProductsArr));`
   ` } else {`
    `localStorage.removeItem("unknown");`
    `localStorage.setItem("unknown", JSON.stringify(newAddedProductsArr));`
    `}`
