### ISSUE TITLE
Error if new user click on cart page

### ISSUE THREAD

**Issue by kitks** [miyabitanimchi/ciccc-react-midterm-team-project#29]
![image](https://user-images.githubusercontent.com/76936712/121294969-1a377a80-c8a3-11eb-8e8f-eebca41394e3.png)

Error if new user click on cart page

**Comment by miyabitanimchi** [comment]
- **Problem Detail:** When a user goes to the cart page without visiting the detail page (when there is no array with the keyName of user's uid or "unknown" in localStorage), the error "Cannot read property "length" of null" occurs.

- **Cause:** Since there is no array in localStorage, null is returned by getItem() and still set by setProductsAddedToCart() .
`if (user) {    `
  `setProductsAddedToCart(JSON.parse(localStorage.getItem(user.uid))); `
 `} else { `
`setProductsAddedToCart(JSON.parse(localStorage.getItem("unknown"))); `
 `  }`

- **Solution**: Added conditionals like below:
` if (user && localStorage.hasOwnProperty(user.uid)) {`
` setProductsAddedToCart(JSON.parse(localStorage.getItem(user.uid)));`
`} else if (localStorage.hasOwnProperty("unknown")) {`
` setProductsAddedToCart(JSON.parse(localStorage.getItem("unknown")));`
`    }`
